import { build } from 'esbuild';
import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const here = new URL('../', import.meta.url).pathname;
const out = resolve(process.argv[2] || '../fleetops-redesign-preview.html');
const bundle = await build({ entryPoints: [resolve(here, 'design/preview.tsx')], bundle: true, write: false, minify: true, format: 'iife', platform: 'browser', jsx: 'automatic', define: { 'process.env.NODE_ENV': '"production"', 'import.meta': '{}'  } });
const assets = await readdir(resolve(here, 'dist/assets'));
const css = await readFile(resolve(here, 'dist/assets', assets.find(p => p.endsWith('.css'))), 'utf8');
const previewCSS = `
.preview-toolbar{position:sticky;top:0;z-index:45;padding:14px 24px;background:#fff;border-bottom:1px solid #dce4ef;display:flex;justify-content:space-between;align-items:center;gap:15px;font-family:Inter,system-ui,sans-serif}
.preview-toolbar strong{display:block;font-size:14px;color:#1a2e50}.preview-toolbar span{display:block;font-size:12px;color:#64748b;margin-top:4px}.preview-device-controls{display:flex;gap:6px}.preview-device-controls button{display:flex;align-items:center;gap:6px;padding:10px;border:1px solid #dce4ef;border-radius:7px;font-size:12px;color:#475569}.preview-device-controls button[aria-pressed=true]{background:#eef3ff;border-color:#adc0ff;color:#2859e8}.preview-frame .fleet-sidebar{top:76px}.preview-phone{max-width:430px;margin:26px auto;border:1px solid #d5ddea;border-radius:22px;overflow:hidden;box-shadow:0 16px 55px #10203915}.preview-phone .fleet-sidebar{display:none}.preview-phone .admin-workspace{margin-left:0}.preview-phone .workspace-topbar{padding:10px 16px;min-height:60px}.preview-phone .admin-content{padding:24px 16px}.preview-phone .topbar-role{display:none}.preview-phone .mobile-menu{display:block}.preview-phone .metric-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.preview-phone .metric-card{padding:17px 15px}.preview-phone .metric-value{font-size:31px}.preview-phone .dashboard-columns{display:flex;flex-direction:column}.preview-phone .dashboard-side{display:flex;flex-direction:column;width:100%}.preview-phone .page-heading{flex-wrap:wrap;gap:16px}.preview-phone .page-heading h1{font-size:27px}.preview-phone .dashboard-refresh{flex-direction:row;align-items:center;gap:12px}.preview-phone .trip-vehicle-icon,.preview-phone .trip-chevron{display:none}.preview-phone .recent-trip{padding:17px 16px}.preview-phone .surface-heading{padding:19px 16px}.preview-phone .workspace-footer{margin:0 16px}.preview-phone .surface{width:100%}@media(max-width:640px){.preview-toolbar{padding:12px 16px;flex-wrap:wrap}.preview-toolbar span{max-width:320px}.preview-phone{margin:0;border:0;border-radius:0}.preview-device-controls{display:none}}
`;
const script = bundle.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const html = `<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>FleetOps · Vista previa del rediseño</title><meta name="description" content="Propuesta visual de FleetOps. Datos ficticios; sin conexión al sistema."><style>${css}\n${previewCSS}</style></head><body><div id="root"></div><script>${script}</script></body></html>`;
await writeFile(out, html);
console.log(`Preview created: ${out} (${Buffer.byteLength(html)} bytes)`);
